import modelsJson from "../../../data/models.json";
import gpusJson from "../../../data/gpus.json";
import laptopsJson from "../../../data/laptops.json";
import type { ModelSpec } from "../compat/types";
import { gpuSchema, gpusFileSchema, laptopSchema, laptopsFileSchema, modelsFileSchema } from "./schema";
import type { z } from "zod";

export type GpuEntry = z.infer<typeof gpuSchema>;
export type LaptopEntry = z.infer<typeof laptopSchema>;

/**
 * Parsed once at module load. A schema mismatch throws here rather than
 * letting a renamed field read as undefined and render 0 GB — the data is
 * regenerated by a scheduled job, so failing loudly is the whole point.
 */
function parse<T>(schema: { parse(v: unknown): T }, raw: unknown, what: string): T {
  try {
    return schema.parse(raw);
  } catch (cause) {
    throw new Error(`data/${what}.json does not match its schema`, { cause });
  }
}

const models = parse(modelsFileSchema, modelsJson, "models").models as ModelSpec[];
const gpus = parse(gpusFileSchema, gpusJson, "gpus").gpus;
const laptops = parse(laptopsFileSchema, laptopsJson, "laptops").laptops;

export function loadModels(): ModelSpec[] {
  return models;
}
export function loadGpus(): GpuEntry[] {
  return gpus;
}
export function loadLaptops(): LaptopEntry[] {
  return laptops;
}
